"""Add district to address

Revision ID: 56349d479152
Revises: cd83907b83ce
Create Date: 2026-08-19 17:56:32.300342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56349d479152'
down_revision = 'cd83907b83ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=8),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=11, scale=8),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('addresses_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('addresses_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.alter_column('longitude',
               existing_type=sa.Numeric(precision=11, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Numeric(precision=10, scale=8),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('city')
        batch_op.drop_column('district')

    # ### end Alembic commands ###
