"""Add reset_token fields to users

Revision ID: 994881c2d6d4
Revises: 17bde1d5b739
Create Date: 2026-08-21 11:01:25.348180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994881c2d6d4'
down_revision = '17bde1d5b739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')
    # ### end Alembic commands ###
