FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH=/app/src/backend

EXPOSE 5000

CMD ["python", "-m", "flask", "--app", "src/backend/app", "run", "--host=0.0.0.0", "--port=5000"]